# Generated by Django 3.1.4 on 2021-01-24 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Base Models',
            },
        ),
        migrations.CreateModel(
            name='BakeryItem',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bakery.basemodel')),
                ('cost_price', models.FloatField(blank=True, max_length=64, null=True)),
                ('sell_price', models.FloatField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bakery Items',
            },
            bases=('bakery.basemodel',),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bakery.basemodel')),
                ('price', models.FloatField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
            bases=('bakery.basemodel',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(blank=True, null=True)),
                ('payable_amount', models.FloatField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bakeryitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.bakeryitem')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.IntegerField(blank=True, null=True)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bakery.ingredient')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='IngredientsBakeryItemMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.IntegerField(blank=True, null=True)),
                ('bakeryitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.bakeryitem')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.ingredient')),
            ],
            options={
                'verbose_name_plural': 'Ingredient Bakery Item Mappings',
            },
        ),
    ]
